# Generated by Django 5.0.6 on 2024-07-03 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
    ]
